name: 'Run all tests on pull requests'
run-name: ${{ github.actor }} initiated a pull request

on:
  workflow_dispatch:
  pull_request:

env:
  IMAGE_NAME: ghcr.io/dafessor/devops-demo-img

jobs:
  chk_devcontainer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check dev container
        run: .github/scripts/check_dev_container.sh ${{ secrets.GITHUB_TOKEN }}
