name: 'Run all tests on pull requests'
run-name: ${{ github.actor }} initiated a pull request

on:
  workflow_dispatch:
  pull_request:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/devops-demo-img:latest

jobs:

  chk_devcontainer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check dev container
        run: .github/scripts/check_dev_container.sh ${{ github.repository}} ${IMAGE_NAME} ${{ secrets.GITHUB_TOKEN }}

  run_tests:
    runs-on: ubuntu-latest
    needs: chk_devcontainer
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Pull dev container
        run: docker pull ${IMAGE_NAME}:latest
      - name: Run tests inside container
        run: docker run --rm --mount type=bind,src=${{ github.workspace }},dst=/workspace ${IMAGE_NAME}:latest sh -c "cd /workspace;mvn test"
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: target/site/jacoco/
          retention-days: 21

  update_coverage_report:
    needs: run_tests
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/test-coverage-report.yml
